spring:
  application:
    name: library
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost/monitor'
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: 'jdbc:postgresql://localhost/monitor'
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration
  jackson:
    serialization:
      fail-on-empty-beans: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      unwrap-root-value: false
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
