
--
-- Name: policy; Type: TABLE; Schema: public; Owner: testuser
--

CREATE TABLE public.policy (
    id integer NOT NULL,
    policytext text
);

ALTER TABLE public.policy OWNER TO testuser;

ALTER TABLE public.policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
