--
-- Name: claim; Type: TABLE; Schema: public; Owner: testuser
--

CREATE TABLE public.claim
(
    id        integer NOT NULL,
    claimtext text
);


ALTER TABLE public.claim OWNER TO testuser;

ALTER TABLE public.claim ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.claim_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
